name: Start Server and Send Email

on:
  schedule:
    # 10分ごとに実行
    - cron: '*/10 * * * *'

jobs:
  start-server:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # このジョブのタイムアウト時間
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Node.js version

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: node backend/server.js
