name: Start Server and Send Email

on:
  schedule:
    # 日本時間の朝8時に実行 (UTCの前日の23時)
    # - cron: '0 23 * * *'
    # # 日本時間の昼12時に実行 (UTCの当日の3時)
    # - cron: '0 3 * * *'
    # # 日本時間の夜8時に実行 (UTCの当日の11時)
    # - cron: '0 11 * * *'

    - cron: '*/10 * * * *' # 10分ごとに実行

jobs:
  start-server:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # このジョブのタイムアウト時間
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Node.js version

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: node backend/server.js
