name: Start Server and Send Email Every Evening

on:
  schedule:
    # 毎晩0:00 AMに実行 (UTC 時間)
    - cron: '0 0 * * *'

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Node.js version

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: node backend/server.js
